version: "0.1"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - ENV=production
      - PORT=8000
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    networks:
      - lucent-net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks:
      - lucent-net
    depends_on:
      - backend
    restart: unless-stopped

networks:
  lucent-net:
    driver: bridge